### ISSUE TITLE
F-score

### ISSUE THREAD

**Issue by YapingZ** [weirme/FCSN#3]
Hello, your code is not complete, your test code does not get the accuracy rate and the recall rate.

**Comment by weirme** [comment]
Yes, F-score can be calculated by json files saved in score_dir. But my evaluation code is quite messy, I may rewrite and upload it after final exam of this semester. If you are in a hurry to use it, please leave your email and I will send it to you as soon as possible!

**Comment by SinDongHwan** [comment]
@SSSTEWARDDD 
you're student?? Wow!!
if you're okay, can i write code and pull request??

Take a good look at the exam!!

**Comment by YapingZ** [comment]
Thank you, because my research direction is this, I have been thinking about doing this in the near future. If you can send the test code to me, thank you very much. My email address is 793991752@qq.com

**Comment by weirme** [comment]
> @SSSTEWARDDD
> you're student?? Wow!!
> if you're okay, can i write code and pull request??
> 
> Take a good look at the exam!!

Thank you so much if you can provide your code and I will try my best to prepare for the exam!

**Comment by weirme** [comment]
> Thank you, because my research direction is this, I have been thinking about doing this in the near future. If you can send the test code to me, thank you very much. My email address is [793991752@qq.com](mailto:793991752@qq.com)

I have sent the code to your email, hope it can help you!

**Comment by fegler** [comment]
@SSSTEWARDDD 
If you don't mind, could I also get your test code?
And I wonder your code performance is similar to paper

Thank you and I also hope you take a good look at the exam!

**Comment by weirme** [comment]
> @SSSTEWARDDD
> If you don't mind, could I also get your test code?
> And I wonder your code performance is similar to paper
> 
> Thank you and I also hope you take a good look at the exam!

You can download my evaluation code from [here](https://drive.google.com/file/d/1iDonDlcFfzXfPyyHy1UUo9JD3ctDJyZf/view?usp=sharing)

**Comment by lovelingclear** [comment]
I am facing with this qunestion "RuntimeError: expected a non-empty list of Tensors". Can you help me, thanks!

**Comment by SinDongHwan** [comment]
please, explain more detailed.
( e.g. which situation, where line in code, etc )

**Comment by lovelingclear** [comment]
> 拜托，解释得更详细。
> （例如，哪种情况，代码行等）

Traceback (most recent call last):
  File "train.py", line 119, in <module>
    solver.train()
  File "train.py", line 73, in train
    mean_loss = torch.stack(sum_loss_history).mean().item()
RuntimeError: expected a non-empty list of Tensors

**Comment by SinDongHwan** [comment]
1. Did you just execute code without editing?
2. Did you download dataset?
3. Did you load dataset correctly?

p.s. I want to make new issue. because this issue is about F-Score.

**Comment by Maruidear** [comment]
> > 拜托，解释得更详细。
> > （例如，某些情况下，代码行等）
> 
> 追溯（最近一次通话最近）： solver.train（）中的
> 文件“ train.py”，第119 行，火车中的文件“ train.py”，行73， mean_loss = torch.stack（sum_loss_history）.mean（）。item （） RuntimeError：预期张量的非空列表

I have encountered the same problem. How did you solve it？

**Comment by iamgmujtaba** [comment]
> > @SSSTEWARDDD
> > If you don't mind, could I also get your test code?
> > And I wonder your code performance is similar to paper
> > Thank you and I also hope you take a good look at the exam!
> 
> You can download my evaluation code from [here](https://drive.google.com/file/d/1iDonDlcFfzXfPyyHy1UUo9JD3ctDJyZf/view?usp=sharing)

Hi @weirme 
Can not open the link ~ can you share the link again 
thanks

**Comment by zhw2020913** [comment]
Can someone please tell me, is the F-core code of the warehouse updated at present? I use my own dataset for experiments and the F-core is always 0
