### ISSUE TITLE
index 5866 is out of bounds for axis 0 with size 5846

### ISSUE THREAD

**Issue by gurunatraj** [weirme/FCSN#31]
Traceback (most recent call last):
  File "gen_summary.py", line 112, in <module>
    gen_summary()
  File "gen_summary.py", line 104, in gen_summary
    get_keys(id)
  File "gen_summary.py", line 50, in get_keys
    keyshots.append(frames[i])
IndexError: index 5866 is out of bounds for axis 0 with size 5846

Any idea how to solve this?

**Comment by pandababyer** [comment]
Hello, i think it is the Inconsistent between the video ID in original videos and fcsn_tvsum.h5. For example video_7 and sTEELN-vY30.mp4.

**Comment by JuJiHyun** [comment]
Hi, Did you solved this problem??
