### ISSUE TITLE
IndexError: index 202 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by solankishweta2910** [weirme/FCSN#35]
I tried running module gen_summary.py

Traceback (most recent call last):
  File "C:/Users/Sachin/Documents/MTech Dissertation/Video_Summary_using_FCSN/gen_summary.py", line 112, in <module>
    gen_summary()
  File "C:/Users/Sachin/Documents/MTech Dissertation/Video_Summary_using_FCSN/gen_summary.py", line 104, in gen_summary
    get_keys(id)
  File "C:/Users/Sachin/Documents/MTech Dissertation/Video_Summary_using_FCSN/gen_summary.py", line 50, in get_keys
    keyshots.append(frames[i])
IndexError: index 202 is out of bounds for axis 0 with size 0

getting the above error.
pls help in solving .

**Comment by 1014763456** [comment]
After you are download the tvsum dataset, you need to rename the video name like 1、2、3. The 1-50 corresponds to the same order in ydata-tvsum50.mat, which is the original matlab file provided by TVSum.https://github.com/KaiyangZhou/vsumm-reinforce/issues/1#issuecomment-380371730
And then you can run the gen_summary.py. I hope it can be helpful.

**Comment by 1014763456** [comment]
> I tried running module gen_summary.py
> 
> Traceback (most recent call last): File "C:/Users/Sachin/Documents/MTech Dissertation/Video_Summary_using_FCSN/gen_summary.py", line 112, in gen_summary() File "C:/Users/Sachin/Documents/MTech Dissertation/Video_Summary_using_FCSN/gen_summary.py", line 104, in gen_summary get_keys(id) File "C:/Users/Sachin/Documents/MTech Dissertation/Video_Summary_using_FCSN/gen_summary.py", line 50, in get_keys keyshots.append(frames[i]) IndexError: index 202 is out of bounds for axis 0 with size 0
> 
> getting the above error. pls help in solving .
After you are download the tvsum dataset, you need to rename the video name like 1、2、3. The 1-50 corresponds to the same order in ydata-tvsum50.mat, which is the original matlab file provided by TVSum.https://github.com/KaiyangZhou/vsumm-reinforce/issues/1#issuecomment-380371730
And then you can run the gen_summary.py. I hope it can be helpful.

**Comment by hpppppp8** [comment]
> I tried running module gen_summary.py
> 
> Traceback (most recent call last): File "C:/Users/Sachin/Documents/MTech Dissertation/Video_Summary_using_FCSN/gen_summary.py", line 112, in gen_summary() File "C:/Users/Sachin/Documents/MTech Dissertation/Video_Summary_using_FCSN/gen_summary.py", line 104, in gen_summary get_keys(id) File "C:/Users/Sachin/Documents/MTech Dissertation/Video_Summary_using_FCSN/gen_summary.py", line 50, in get_keys keyshots.append(frames[i]) IndexError: index 202 is out of bounds for axis 0 with size 0
> 
> getting the above error. pls help in solving .

After you are download the tvsum dataset, you need to rename the video name like 1、2、3. The 1-50 corresponds to the same order in ydata-tvsum50.mat, which is the original matlab file provided by TVSum.https://github.com/KaiyangZhou/vsumm-reinforce/issues/1#issuecomment-380371730
And then you can run the gen_summary.py. I hope it can be helpful.
